### ISSUE TITLE
Couldn't create a unique link for text, selected with a triple-click

### ISSUE THREAD

**Issue by ytanikin** [GoogleChromeLabs/link-to-text-fragment#1]
There is an alert when you try to create a link on the text that was selected by triple-click with the left button of the mouse on any site.

Steps to reproduce

1. Open any site with text, for example, Wikipedia
2. Press the left button three times 
3. Press the right button, choose "Copy link to selected text"

**Comment by tomayac** [comment]
Thanks for opening the issue. After some investigation, this is actually not a problem with the extension, but a Chrome bug where triple-clicked selections apparently don't properly register. I have filed https://crbug.com/1096980 for you. Please star (or CC: yourself) to this bug. I'm closing the present issue in favor of the Chrome bug.
