### ISSUE TITLE
Fragment + directive-delimited URIs don't function.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GoogleChromeLabs/link-to-text-fragment#100]
For instance, https://wiki.archlinux.org/index.php?title=Steam/Troubleshooting&oldid=804434#Debugging_Steam:~:text=%24-,debugger%3Dgdb%20steam,-gdb%20will%20open doesn't take me to https://wiki.archlinux.org/index.php?title=Steam/Troubleshooting&oldid=804434#Debugging_Steam, nor does it highlight https://wiki.archlinux.org/index.php?title=Steam/Troubleshooting&oldid=804434#:~:text=%24-,debugger%3Dgdb%20steam%20,-gdb%20will%20open.

I'm using https://addons.mozilla.org/firefox/downloads/file/3969185/link_to_text_fragment-2.3.2.xpi on https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0.1-1.1.x86_64.rpm (but it doesn't work on `google-chrome-unstable-125.0.6368.2-1` either). To my knowledge, it did work for a short while when this extension was first released, but hasn't for some time.

Important due to https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/92#issue-1855854321.

**Comment by tomayac** [comment]
Chrome's built-in feature creates…

`https://wiki.archlinux.org/index.php?title=Steam/Troubleshooting&oldid=804434#Debugging_Steam:~:text=%24-,DEBUGGER%3Dgdb%20steam,-gdb`

…and the extension creates…

`https://wiki.archlinux.org/index.php?title=Steam/Troubleshooting&oldid=804434#Debugging_Steam:~:text=%24-,debugger%3Dgdb%20steam,-gdb%20will%20open`

**Comment by tomayac** [comment]
This looks like a browser issue. For Chrome, I have filed https://issues.chromium.org/issues/331237013. Feel free to copy this bug text and create a Firefox bug. Thanks!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/100#issuecomment-2019848938

@tomayac, https://bugzilla.mozilla.org/show_bug.cgi?id=1887968#c0.
