### ISSUE TITLE
Duplicates selected text into clipboard (instead of URI) at specific URI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GoogleChromeLabs/link-to-text-fragment#101]
Using https://kojipkgs.fedoraproject.org//packages/firefox/124.0.2/2.fc40/x86_64/firefox-124.0.2-2.fc40.x86_64.rpm, I visited https://www.linkedin.com/in/rokejulianlockhart/details/publications/edit/forms/298324074/?profileFormEntryPoint=PROFILE_SECTION (you should be able to see the same thing if you edit an entry of yours in the "Publications" section of your LinkedIn profile) and select any of the pop-up form:

> ![image](https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/42837531/e263ed9a-9c91-4d1e-8b7f-39933f98104c)

When I use https://addons.mozilla.org/firefox/downloads/file/3969185/link_to_text_fragment-2.3.2.xpi, instead of a fragment-delimited URI being duplicated to the clipboard

> Edit publication
> 
> * Indicates required 

<details>

<blockQuote>

```HTML
<h2 id="profile-edit-form-page-header">
          <!---->Edit publication<!---->
      </h2>
```

</blockQuote>

<blockQuote>

```HTML
<p class="t-12 t-black--light">
      * Indicates required
    </p>
```

</blockQuote>

</details>

is.

**Comment by tomayac** [comment]
This is probably LinkedIn populating the clipboard to be helpful.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/101#issuecomment-2055866233

@tomayac, is there a way to verify? Regardless, it renders the extension useless.

**Comment by tomayac** [comment]
You would need to traverse the source code. Since your LinkedIn is completely different than my LinkedIn, there's not much you could link to anyway. Also, LinkedIn oftentimes ends you up on a login wall. The extension can't circumvent that.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/101#issuecomment-2056245213

@tomayac, I only intended to use the URI for myself.
