### ISSUE TITLE
Broken formatting of `<ul>` in `Reddit.com` comments.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GoogleChromeLabs/link-to-text-fragment#102]
#### Preparation

1.	https://kojipkgs.fedoraproject.org//packages/firefox/125.0.2/1.fc40/x86_64/firefox-125.0.2-1.fc40.x86_64.rpm
1.	https://addons.mozilla.org/firefox/downloads/file/3969185/link_to_text_fragment-2.3.2.xpi

#### Example

1.	#### https://www.reddit.com/r/fossdroid/comments/vuf9ci/comment/ifgks0b/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

	> ![screenshot-www reddit com-2024 04 27-22_17_51](https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/42837531/dfbfd4a5-0b82-48ec-9a42-7e190c2f9775)

	becomes

1.	#### https://www.reddit.com/r/fossdroid/comments/vuf9ci/comment/ifgks0b/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button#:~:text=I%20will%20ask,and%20Neo%20Store.

	> ![screenshot-www reddit com-2024 04 27-22_17_17](https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/42837531/785ad1f9-8dbb-4e50-a1c2-2a3fc15635c6)

**Comment by tomayac** [comment]
The extension needs to insert `<mark>` elements to simulate native text fragment highlighting on browsers that don't support the feature natively yet, which, unfortunately, seems to not work well with Reddit's CSS. Once native support lands in Firefox, this should no longer be necessary, and the native highlighting feature will be used automatically. For reference, the screenshot below shows how it looks like in Chrome now, and Firefox will hopefully soon produce the same result:

![Screenshot 2024-04-29 at 09 22 41](https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/145676/61284757-7973-42bb-ab51-c6e859fada93)
