### ISSUE TITLE
Add context menu item to clear highlight

### ISSUE THREAD

**Issue by pointydev** [GoogleChromeLabs/link-to-text-fragment#104]
Hey there,

Would be great to have a context menu item in the extension to clear highlighted text after loading a page with a fragment, much like in the native Chromium implementation.

Thanks,
Elliott

**Comment by tomayac** [comment]
Chrome and Safari support this natively, and [Firefox is about to](https://bugzilla.mozilla.org/show_bug.cgi?id=1753933), so I don't think it's a feature worth adding now, since the extension will just use the native implementation.
