### ISSUE TITLE
Can we get updates as per TPW's methodology if not via the Chrome Web Store? 

### ISSUE THREAD

**Issue by ylluminate** [GoogleChromeLabs/link-to-text-fragment#106]
Would love to see an update that brings this extension back into working order. Wondering if the effort is already done and you've having trouble getting it through Google? Maybe it would be good to facilitate a method of deployment like these guys for users of Ungoogled Chromium with auto extension updates via [Chromium Web Store](https://github.com/NeverDecaf/chromium-web-store) such as myself:
https://github.com/FilipePS/Traduzir-paginas-web

**Comment by tomayac** [comment]
The reason it's broken somewhat since migrating to manifest v3 is outlined in https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/93#issuecomment-1702526925. It's not a problem related to updates.
