### ISSUE TITLE
Extension update on Mozilla addons

### ISSUE THREAD

**Issue by yozachar** [GoogleChromeLabs/link-to-text-fragment#108]
![image](https://github.com/user-attachments/assets/6b28d7b9-f782-4572-b1f9-1520f0191f7a)

Has it not been updated on Mozilla addons?

**Comment by tomayac** [comment]
I tried, but unfortunately Firefox doesn't support the extension in its current form (that is, with a background service worker). CC: @dotproto 

[Validation Results for Archive.zip __ Developer Hub __ Add-ons for Firefox.pdf](https://github.com/user-attachments/files/17374307/Validation.Results.for.Archive.zip.__.Developer.Hub.__.Add-ons.for.Firefox.pdf)

**Comment by tomayac** [comment]
This is the extension source code if you want to try at home.
 
[Archive.zip](https://github.com/user-attachments/files/17374323/Archive.zip)

**Comment by dotproto** [comment]
Currently commuting, but LMK if you need more info and I will follow up.

It's possible to use both a service worker in Chrome and an event page in Firefox/Safari by declaring both in the manifest:

```json
  "background": {
    "scripts": ["background.js"],
    "service_worker": "background.js"
  }
```

That should cover the vast majority of the browser incompatibly.

**Comment by tomayac** [comment]
Thanks to @dotproto's tip I was now able to update the extension on Firefox as well: https://addons.mozilla.org/addon/link-to-text-fragment/. Thanks both!

**Comment by kevin-wijnen** [comment]
> Thanks to @dotproto's tip I was now able to update the extension on Firefox as well: https://addons.mozilla.org/addon/link-to-text-fragment/. Thanks both!

Any update on the patch's deployment? Seems like the Firefox Extension has not gotten an update in 2 years according to its page.

![image](https://github.com/user-attachments/assets/9dde0ca5-6c24-43e1-a466-bfa79d1c1ee3)

**Comment by tomayac** [comment]
Please see the thread from https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/95#issuecomment-2422369268 onward.

**Comment by kevin-wijnen** [comment]
> Please see the thread from [#95 (comment)](https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/95#issuecomment-2422369268) onward.

Thanks for referring it - seems like I somehow still had the broken 2.5.0 on my machine. Reinstalling from the Firefox page managed to rollback to the current version on it with it working again! :pray:
