### ISSUE TITLE
The extension should work offline also

### ISSUE THREAD

**Issue by jidanni** [GoogleChromeLabs/link-to-text-fragment#12]
The extension should be tested to make it work offline.
E.g., if we are browsing file:///home/xyz.html
then we should be able to make perfectly legitimate
file:///home/xyz.html#bla_bla links.

No matter for testing, or interpage linking, the extension should work
perfectly fine offline too.

**Comment by tomayac** [comment]
Go to `chrome://extensions`, find the Link to Text Fragment extension and click the Details button. There is a switch that allows you to turn the extension on for `file://` URLs:

<img width="678" alt="Screen Shot 2020-09-14 at 08 37 39" src="https://user-images.githubusercontent.com/145676/93051985-a5157c80-f665-11ea-9715-2788d8d8ba79.png">
