### ISSUE TITLE
Alert upon failure

### ISSUE THREAD

**Issue by jidanni** [GoogleChromeLabs/link-to-text-fragment#13]
If for some reason it is not possible to make a link,
the extension should at least
issue an alert, instead of doing nothing.

Else the user will just end up fruitlessly trying to paste what he discovers
is not what he intended.

**Comment by tomayac** [comment]
It *should* always show an alert when something goes wrong. Do you have a URL and text selection that reproducibly fails without showing an alert? Also note that extensions can't work on any of the Chrome Web Store pages for security reasons.

**Comment by jidanni** [comment]
Ah, it was the case of #12.
Odd, if the extension was disabled on local file: pages, then how come it still was able to alter the right click menu there, but then unable to issue the alert (that it was unable to deal with this local page until the user flipped the switch.)

**Comment by jidanni** [comment]
> Also note that extensions can't work on any of the Chrome Web Store pages for security reasons.

OK, but also do something about the right click menu entry when browsing there too.

In fact maybe the icon in the toolbar to the right of the URL bar should change from colored to black and white, to indicate we cannot operate on the current page (file: pages too.) (Alas, the icon is already black and white. So make a new colored on be the default, perhaps.)

**Comment by tomayac** [comment]
I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1127865 for this.
