### ISSUE TITLE
Offer also plain scroll-to-id mode, in addition to scroll-to-text-fragment mode

### ISSUE THREAD

**Issue by jidanni** [GoogleChromeLabs/link-to-text-fragment#14]
I should have submitted https://github.com/WICG/scroll-to-text-fragment/issues/144 here, they say.

**Comment by tomayac** [comment]
There already is an extension for linking to arbitrary elements: [Link to Element](https://chrome.google.com/webstore/detail/link-to-element/enadmddipfodpmlnaajhofpkiephdhhe/). It uses XPath to link to *any* element, but if the element in question has an `id`, it will use it.

**Comment by tomayac** [comment]
Here's an example link I have just created with this extension: https://wiki.debian.org/resolv.conf#Configuring_resolvconf.

**Comment by jidanni** [comment]
Well that is nice. However:
(Note to myself: it puts what it creates into the URL bar. Look there instead of the clipboard).
Apparently it can create:
* Nothing, if there is nothing for it to grab onto
* Xpaths, which only work when shared to chrome users. Firefox didn't recognize them.
* That \#Configuring_resolvconf fragment, if apparently one places the cursor just right before right clicking.

**Comment by tomayac** [comment]
> Well that is nice. However:
> (Note to myself: it puts what it creates into the URL bar. Look there instead of the clipboard).

Yes, this particular extension changes the URL bar. There are probably other extensions that work with the clipboard, this is simply the first one that I have found after 30s of searching…

> Apparently it can create:
> 
> * Nothing, silently, if there is nothing for it to grab onto
> * Xpaths, which only work when shared to chrome users. Firefox didn't recognize them. Wait: chrome users need to have the extension installed too. My whole goal is to share things (with grandparents, etc. who don't have extensions installed.)

If you want cross-browser compatible links, you're bound to `id`- or `name`-based linking. 

> * That #Configuring_resolvconf fragment, if apparently one places the cursor just right before right clicking.
> 
> Anyway, there ought to be an extension showing the red boxes, and then allowing copying links to them.

I'm sure there is, just needs some searching.
