### ISSUE TITLE
Control+Shift+L clashes with Google Docs shortcut

### ISSUE THREAD

**Issue by Henry-Gooseleg** [GoogleChromeLabs/link-to-text-fragment#15]
When I do ctrl+shift+l to left align on Google Docs, the popup appears telling me I haven't selected anything to copy the link to. This also prevents the shortcut from working (the text is still center aligned). I am on a Chromebook, if that has anything to do with the shortcut not working. I'm a little disappointed that 3 Google products clash and don't work together properly.

**Comment by tomayac** [comment]
You can customize the extension’s shortcut by pasting `chrome://extensions/shortcuts` into the URL bar. You can then choose something that doesn’t clash with other apps.

**Comment by samdutton** [comment]
Might be worth adding this to the extension overview — I had the same problem.

**Comment by tomayac** [comment]
I'm all open to a new shortcut default. Any ideas? My idea was to have something with an 'L' for "**L**ink to Text Fragment".

**Comment by samdutton** [comment]
Maybe no default shortcut, but explain how to add one?

(I just right-click — might be worth making that method really clear.)

**Comment by Titan21** [comment]
Hi, I also just came here to complain about the clashing shortcut, and the inability to change it.
I never knew there's a way to configure Shortcuts to Chrome Extensions.
Unfortunately I'd say don't configure a default shortcut unless there's a way in the Extension options
![image](https://user-images.githubusercontent.com/598683/96393190-e5df5300-121a-11eb-867d-4b04d8b3dfc2.png)
to change / disable the shortcut or point to chrome://extensions/shortcuts

**Comment by tomayac** [comment]
Thanks for the input. I've removed the suggested default hotkey, which means there won't be a clash anymore for all users, and power users can still set their own preferred hotkey. The new version will be released in the next days.

**Comment by SmartManoj** [comment]
> I'm all open to a new shortcut default. Any ideas? My idea was to have something with an 'L' for "**L**ink to Text Fragment".

Ctrl Shift F

**Comment by SmartManoj** [comment]
> Thanks for the input. I've removed the suggested default hotkey, which means there won't be a clash anymore for all users, and power users can still set their own preferred hotkey. The new version will be released in the next days.

[Need to update Pro Tip](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg?hl=en#:~:text=Usage%20instructions%3A%20%E2%80%A2%20Select%20the,you%20want%20to%20link%20to.&text=Right%2Dclick%20and%20choose%20%22Copy,Text%22%20from%20the%20context%20menu.&text=If%20the%20link%20creation%20succeeded,be%20briefly%20highlighted%20in%20yellow.&text=Paste%20your%20link%20wherever%20you%20want%20to%20share%20it.)

**Comment by tomayac** [comment]
Thank you for the reminder, I have updated the pro-tip and the change should go live once the new description gets approved.
