### ISSUE TITLE
Unable to Use   "#1:~:text=" in same page 

### ISSUE THREAD

**Issue by krishna-pearl** [GoogleChromeLabs/link-to-text-fragment#16]
I'm using a # 1:~:text=  to link the important list at the last of my doc but can't.

**Comment by krishna-pearl** [comment]
With Extension  The Copy Url is - xyz.com #comp-k7nn0tbe:~:text=Snook%20Streams
**comp-k7nn0tbe**  not working for me.

**Comment by tomayac** [comment]
Please note that Text Fragment URLs only work for non-same-page navigations that were the result of a user gesture ([source](https://web.dev/text-fragments/#security:~:text=Text%20fragment%20directives%20are%20invoked%20only,result%20of%20a%20user%20activation.)). Try pasting your link in a new tab and it should work.

**Comment by krishna-pearl** [comment]
what about  the **#comp-k7nn0tbe**  before   **:~:text=**

**Comment by tomayac** [comment]
`#comp-k7nn0tbe` is an element fragment, `:~:text=` is a text fragment. The text fragment has priority over the element fragment.

**Comment by krishna-pearl** [comment]
Using element fragment is important?

**Comment by tomayac** [comment]
Please read the [relevant part of the article](https://web.dev/text-fragments/#mixing-element-and-text-fragments) to find an answer to this question. In short: it's a backup option should the text fragment not be found.

**Comment by krishna-pearl** [comment]
Can we link images using the " :~:text=" ?
If I use this in m back ens will it work?

**Comment by tomayac** [comment]
As the name suggests, you can link to text only at the moment. You can, of course, link to the closest text next to an image. There's some thinking on the team to allow for other directives like `:~:img`, but this is for the future. Text Fragment URLs are a browser feature meant to work in the browser. You can, of course, create such URLs in your back-end.

Please note that this is an Issue thread, not a general support forum. A lot, if not all, of your questions are answered in the [article](https://web.dev/text-fragments/). Thanks!

**Comment by krishna-pearl** [comment]
Thanks
