### ISSUE TITLE
Links that are bound to backfire: pages that need clicks to get to such links

### ISSUE THREAD

**Issue by jidanni** [GoogleChromeLabs/link-to-text-fragment#17]
https://www.usvotefoundation.org/vote/us/state-voting-information/IL#collapseEight:~:text=Overseas%20Voter
will not help _sharees_ get to here,
![13921-0](https://user-images.githubusercontent.com/1230959/95004951-ca722680-0624-11eb-9fd1-220929f0c1c6.jpg)
Because that spot needs a few clicks to get to in the first place, when first visiting the page.

So maybe the app should say in an alert, that sorry, we are not able to give you this link because it wont work, as the page wasn't in the initial state etc...

**Comment by tomayac** [comment]
Unfortunately there’s no way for the extension to replay manual steps that may be required to navigate there. Try finding a spot in the page that’s closest to where someone needs to go, but that’s accessible on-load without user interaction.

**Comment by jidanni** [comment]
(Hmmm so there needs to be "Safety labeling":
"Be sure to check (in an incognito window too) that a link this tool provides will actually work before sharing."
"And also remember _sharees_ might be using different browsers/versions too, so results are not guaranteed.")

**Comment by tomayac** [comment]
If it's *mission-critical* that the link works *exactly* as you see it, then the incognito window check is a good idea. You would need to let the recipient know that they need to use the Chrome browser, too, at the moment.
