### ISSUE TITLE
How to make it working with PDF when opened in browser

### ISSUE THREAD

**Issue by infact** [GoogleChromeLabs/link-to-text-fragment#19]
Did it actually work for pdf file(opened in chromium).? It did not work for me. For HTML files it is working fine.
For PDF file opened in chrome/chromium, it will show the context menu to "copy link to selected text" but actually no link is getting copied.

**Comment by tomayac** [comment]
While PDFs are rendered in a browser tab, they are not webpages, which means the extension cannot run. Unfortunately there is no way to prevent the context menu from appearing. Sorry for this.

**Comment by carlgieringer** [comment]
Could the extension work with PDFs rendered using PDF.js? I think PDF.js works by translating the PDF into HTML (see screenshot below), and that Firefox opens PDFs using PDF.js [by default](https://github.com/mozilla/pdf.js#:~:text=Firefox-,PDF.js%20is%20built,version%2019%2B%20of%20Firefox.,-Chrome).

<img width="1460" alt="Screenshot 2023-08-10 at 9 24 21 AM" src="https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/78054/d1a6deb4-adcd-46b3-a08d-312c33ceb25c">

https://www.supremecourt.gov/opinions/22pdf/22-535_i3kn.pdf

**Comment by tomayac** [comment]
PDF.js in this case is an implementation detail of a specific vendor's PDF viewer, but not generalizable to all vendors. If this use case is essential for you, you can for the extension.
