### ISSUE TITLE
Not generating enough context

### ISSUE THREAD

**Issue by bokand** [GoogleChromeLabs/link-to-text-fragment#2]
Here's an interesting case: 

I was trying to copy a link to [this text](https://github.com/mozilla/standards-positions/issues/194#:~:text=on%20balance.-,The%20marginalia%20use%20case%20described%20at%20https://indieweb.org/marginalia%20is%20not%20supported%20as%20well%20as%20it%20could%20be,%20since%20the%20fragment%20specifier%20is%20stripped%20from%20the%20URL) but the extension gave up due to uniqueness.

Turns out on GitHub it's common to have text quoted which means large sections will be non unique. It's a bit of an edge case for our algorithm.

However, in this case, simply using the last few words of the previous numbered list entry works as disambiguating context. I haven't had a chance to dig into the code yet but it looks like the extension isn't (correctly) crossing the block boundary to find context when the match starts at a block boundary.

**Comment by tomayac** [comment]
I’ll have a look after the weekend.
