### ISSUE TITLE
dynamically build the link

### ISSUE THREAD

**Issue by infact** [GoogleChromeLabs/link-to-text-fragment#22]
is there a way to build programmatically generate link to the highlighted text.
for example:  I am looking to create  C# function that accepts url and the paragraph to be highlighted that returns  the url.

generateLTFlink(string url, string paragraphTobehighlighted){

return ltfurl;
}

here is what I tried so far and it ran 

` public static string GetTextHighLighterUrl(string firstValidFileUrl, string answer)
        {
            var sb = new StringBuilder();
            var textHighLighterUrl = string.Empty;
            var highlightText = answer.Replace(firstValidFileUrl, "");
            highlightText = highlightText.Replace("()", "");
            highlightText = $"{Regex.Replace(highlightText, @"\[[^]]*\]", "")}"; // remove text within square brackets.
            highlightText = $"{Regex.Replace(highlightText, @"\t|\r", "$$")}";
            highlightText = RemoveExtraSentences(highlightText, "$$").Trim();
            highlightText = highlightText.Replace("$$", "");
            highlightText = FilterWhiteSpaces(highlightText);
            highlightText = highlightText.Replace("$", "");
            highlightText = highlightText.Replace("(/)", "");
            highlightText = highlightText.Replace("\"", "%22");
            highlightText = highlightText.Replace(",", "%2C");

            if (!ContainsOnlyAlphaNumericCharacters(highlightText))
            {
                //remove sentences with special char and get a safe sentence
                highlightText = GetCleanSentence(highlightText);
            }

            if (highlightText.Length > 50)
            {
                var textArrayn = highlightText.Split("\n"); //if ans contains \n
                if (highlightText.Contains("\n") && textArrayn?.Length == 2)
                {
                    textArrayn = highlightText.Split("\n");
                }
                else
                {
                    textArrayn = new List<string>().ToArray();
                }
                var textArray = highlightText.Split();
                var n = textArray.Length;
                sb.Clear();
                for (int i = 0; i < 5; i++)
                {
                    if (IsValidIndex(i, textArray))
                    {
                        sb = sb.Append(textArray[i] + "%20");
                    }
                }
                var start = sb.ToString();
                if (start.Contains(","))
                {
                    var tempStart = start.Split(",");
                    start = tempStart[0].ToString();
                }

                if (textArrayn.Length > 0)
                {
                    start = textArrayn[0].ToString();  //if ans contains \n then start from there
                }
                sb.Clear();
                for (int i = n - 6; i <= n; i++)
                {
                    if (IsValidIndex(i, textArray))
                    {
                        if (i != n - 1)
                        {
                            sb = sb.Append(textArray[i] + "%20");
                        }
                        else
                        {
                            sb = sb.Append(textArray[i]);
                        }

                    }
                }
                var end = sb.ToString().Trim();
                end = end.Replace(",", "%2C");
                sb.Clear();
                sb = sb.Append(firstValidFileUrl).Append("#object:~:text=").Append(start).Append(",").Append(end);
                textHighLighterUrl = sb.ToString();
                sb.Clear();
            }
            else
            {
                sb.Clear();
                highlightText = highlightText.Replace(" ", "%20");
                if (!string.IsNullOrEmpty(highlightText))
                {
                    sb = sb.Append(firstValidFileUrl).Append("#object:~:text=").Append(highlightText);
                }
                else
                {
                    sb = sb.Append(firstValidFileUrl);
                }

                textHighLighterUrl = sb.ToString();
                sb.Clear();
            }
            textHighLighterUrl = $"{Regex.Replace(textHighLighterUrl, @"\.{2,}", "")}";//edge cases.Remove Multiple dots
            textHighLighterUrl = textHighLighterUrl.Replace(",%20,", ",");

            return textHighLighterUrl;
        }`

**Comment by tomayac** [comment]
Please see the polyfill library for this, specifically the file [`fragment-generation-utils.js`](https://github.com/GoogleChromeLabs/text-fragments-polyfill/blob/master/src/fragment-generation-utils.js).
