### ISSUE TITLE
algorithm to generate that hyperlink

### ISSUE THREAD

**Issue by infact** [GoogleChromeLabs/link-to-text-fragment#23]
Where can I see the logic that generates the hyperlink from the selected paragraph when we right-click on the selected text. I am trying to see if I can generate that hyperlink programmatically by sending the text to be highlighted as input params. https://stackoverflow.com/questions/64663625/generate-link-to-page-and-highlight-text-with-link-to-text-fragment-plugin

**Comment by tomayac** [comment]
Please refrain from opening new Issues. The answer is already in https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/22#issuecomment-721094194. Thank you.
