### ISSUE TITLE
Interfering with Middle-Click

### ISSUE THREAD

**Issue by potterphx** [GoogleChromeLabs/link-to-text-fragment#27]
While in a web browser I often use the middle mouse click on a link to open the link in a new tab.  However recently this stop working so I have had to start using Ctrl-Click.  I finally decided to search for a solution to this issue.  [One of the first hits I found](https://www.zdnet.com/article/some-google-chrome-extensions-are-blocking-middle-click-actions/) indicated that some extensions can interfere with the middle-click. So I disabled all my extensions to see if this was my issue and found that middle click started working again.  Re-enabling and retesting it ended up being link-to-test-fragment was the culprit.

**Comment by potterphx** [comment]
On attempting to re-test, middle-click is working again.  Therefore it may have been a something else, or the issue may be intermittent.  If it was something else, sorry for the poor issue report.  Only time, or other reporters, will be able to tell if this is an intermittent issue.

**Comment by tomayac** [comment]
This extension only interferes with right-click for context menu ([code](https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/e6960bf2d58388bbc752440aba7852a81d71cb75/background_script.js#L82-L86)). It must have been something else then.
