### ISSUE TITLE
Example link in README doesn't work

### ISSUE THREAD

**Issue by 4U6U57** [GoogleChromeLabs/link-to-text-fragment#3]
I mean this one:

> Try it out by clicking on this link: https://wicg.github.io/ScrollToTextFragment/#ref-for-fragment-directive:~:text=%23%3A~%3Atext%3D%5Bprefix%2D%2C%5DtextStart%5B%2CtextEnd%5D%5B%2C%2Dsuffix%5D.

Seems to be because they renamed the repo to [`wicg/scroll-to-text-fragment`](https://wicg.github.io/scroll-to-text-fragment) and the fragment doesn't make it through the redirect.

**Comment by tomayac** [comment]
Thanks! 🙏
