### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by xhendrikg** [GoogleChromeLabs/link-to-text-fragment#30]
Its doesnt work for example on: https://atlauncher.com/#:~:text=Dec%2016%2C%202020%20%2D%20Microsoft%20accounts%20now%20supported

**Comment by tomayac** [comment]
Works just fine, just tested on Chrome for macOS and Chrome for iOS:

<img width="1498" alt="Screen Shot 2021-04-09 at 14 41 45" src="https://user-images.githubusercontent.com/145676/114181471-d5927000-9941-11eb-8302-f1cbb0f7a28c.png">
