### ISSUE TITLE
Issue with Citrix.com links (with or without # sign)

### ISSUE THREAD

**Issue by invokethebrain** [GoogleChromeLabs/link-to-text-fragment#33]
Using Chrome 89.0.4389.114 (Official Build) (64-bit) (cohort: Stable)
on Windows 10 20H2

Doesn't work on a link like this:
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/1912-ltsr/install-configure/install-command.html#command-line-options-for-installing-a-vda

You will get this:
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/1912-ltsr/install-configure/install-command.html#4:~:text=the%20installer%20resumes%20automatically%20after%20the%20restart%20completes

But it should be this (removed the 4 from #4):
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/1912-ltsr/install-configure/install-command.html#:~:text=the%20installer%20resumes%20automatically%20after%20the%20restart%20completes

No idea where the #4 comes from.

This link works:
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/configure-client-status#configure-alerts

Using right click action gives me this:
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/configure-client-status#configure-alerts:~:text=Select%20the%20collection%20for%20which%20you,in%20the%20Properties%20group%2C%20select%20Properties.

**Comment by invokethebrain** [comment]
Using the experimental function instead of the extension works perfectly fine.
chrome://flags/#copy-link-to-text

**Comment by tomayac** [comment]
Thanks for filing this issue. I’m working on changing the way the link generation works. This should soon fix this present issue and #25. Please bare with me while this is in progress.
