### ISSUE TITLE
Can't create an shortcut to copy the link to the selected text

### ISSUE THREAD

**Issue by dartic2k** [GoogleChromeLabs/link-to-text-fragment#34]
As the tittle says, can't find the option to create the shortcut

**Comment by dartic2k** [comment]
Just to make clear, the options button is greyed out

**Comment by tomayac** [comment]
It’s described for example in this article: https://www.howtogeek.com/127162/how-to-create-custom-keyboard-shortcuts-for-browser-actions-and-extensions-in-google-chrome/.

**Comment by dartic2k** [comment]
thanks a lot, I'll check it out
