### ISSUE TITLE
Opening link right after start firefox doesn't scroll to target

### ISSUE THREAD

**Issue by flyxyz123** [GoogleChromeLabs/link-to-text-fragment#36]
System: windows 10 and arch linux\
Browser: firefox 88.0.1\
Extension version: 2.0.1

## Steps to reproduce
same for private window or not
```
firefox --private-window https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/#:~:text=you%20also%20need%20to%20put%20%5C%5B%20and%20%5C%5D%20around%20any%20color%20codes%20so%20that%20bash%20does%20not%20take%20them%20into%20account%20when%20calculating%20line%20wraps.
```

## Expected behavior
Opening link right after start firefox will scroll to target.

## Actual behavior
Opening link right after start firefox doesn't scroll to target.\
I need to right click and copy another text as link in order to make the extension work.\
Details see attached screen capture video. 

https://user-images.githubusercontent.com/30398651/117910800-72259600-b291-11eb-9dd0-bc80fdb0bf71.mp4

**Comment by flyxyz123** [comment]
In fact, you don't need to open the second link in another tab for the first link to work. Just right click and copy random text as link and refresh the page. The first link will work right away.

**Comment by tomayac** [comment]
Thanks for reporting. There seems to have been some change in Firefox that broke. We are tracking the problem as https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/60 (that's the library the extension uses under the hood). I'm closing the current Issue, please subscribe to the underlying Issue to be notified of changes.
