### ISSUE TITLE
Don't insist on Unique Text (make it an option)

### ISSUE THREAD

**Issue by dbareis** [GoogleChromeLabs/link-to-text-fragment#37]
A lot of time I'd be happy with it working on the first match.  I believe this would be the extension forcing this and not chrome which I'm guessing would go to the first match.

Maybe display the message but still copy the link in case the user is happy with this (that is make it a suggestion rather than an error).

**Comment by tomayac** [comment]
Scroll to Text Fragment is very much about unique links. This is not a "find on page" feature, but really meant to link to _the_ instance of text that someone means to link to.

**Comment by dbareis** [comment]
Google supports it, your extension doesn't.  But you wrote it, maybe when I have more time I'll fork it.

**Comment by tomayac** [comment]
You can get this behavior (see [spec](https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20only%20required%20parameter%20is%20textstart.%20if%20only%20textstart%20is%20specified%2C%20the%20first%20instance%20of%20this%20exact%20text%20string%20is%20the%20target%20text.)), but it's very much not in the sense of this extension.

**Comment by dbareis** [comment]
The behavior I suggested wouldn't change any obvious behavior except perform the copy to clipboard anyway (which wouldn't kill anyone), I have a number of cases where I'm happy to go to the first matching search result.  Either way I can work around it or fork it eventually.  Thanks

**Comment by dbareis** [comment]
Hi,

It's your extension but I thought the sense of the app was to link to text
in a html page.

---
Thanks
Dennis

**Comment by willlma** [comment]
@tomayac would you reconsider this? I installed this extension because I enjoy the scroll to text fragment functionality in Chrome, and wanted the same in Firefox. I generated some links separately based on [the spec](https://web.dev/text-fragments/) and expected them to work. For example, [this link](https://fs.blog/2021/08/remember-books/#:~:text=blank%20sheet%20method) works in Chrome but does not work in Firefox.

**Comment by tomayac** [comment]
I have filed https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/87 about this issue.

**Comment by willlma** [comment]
Thanks!
