### ISSUE TITLE
Created link does not contain dot char, causing it to break

### ISSUE THREAD

**Issue by Snaaio** [GoogleChromeLabs/link-to-text-fragment#38]
I tried to create a link to the following text, but I had to insert the dot character "." after "exception" into the link myself to make it work.

Broken link created via select + right-click > Copy Link to selected text:
https://docs.microsoft.com/en-us/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions#:~:text=execution-,corrupted%20state%20exceptions,-In

Working link after fixing it manually:
https://docs.microsoft.com/en-us/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions#:~:text=execution.-,corrupted%20state%20exceptions,-In

**Comment by tomayac** [comment]
The link generation happens in a library in another repo. I'm closing the present Issue in favor of https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/66. Please subscribe there (I have also mentioned you).
