### ISSUE TITLE
Multiple selections.   (Less of an issue, more of a question)

### ISSUE THREAD

**Issue by GeorgeSpelvin** [GoogleChromeLabs/link-to-text-fragment#39]
In my search results, I'm seeing highlights in multiple areas (e.g. a sentence here, a paragraph there).
([Example from some recent (sad) news](https://www.thesudburystar.com/news/local-news/kamloops-discovery-a-devastating-reminder-of-residential-school-tragedy-sudburys-mayor-says#:~:text=Irene%20Favel%20was%20witness%20to,the%20murder%20of%20a%20newborn.&text=And%20they%20took%20the%20baby%20into%20the%20furnace%20room%2C%20and,could%20smell%20that%20flesh%20cooking.))

How can I do this in my own selecting of text so I can link to those highlighted parts?  I've figured out how to manually enter it in based on the syntax but is there any way to do it with Shift/Ctrl or whatever?

**Comment by tomayac** [comment]
Unfortunately browsers today let you only select one thing at a time, which means you have to manually combine the different highlights (which you have figured out already).
