### ISSUE TITLE
Doesn't break on <br />

### ISSUE THREAD

**Issue by NatoBoram** [GoogleChromeLabs/link-to-text-fragment#40]
I'm trying to make a link to `elle a brisé` on https://leconjugueur.lefigaro.fr/conjugaison/verbe/briser_feminin.html.

If I just put the text at the right place (`#:~:text=elle a brisé`), it doesn't work.

When I use "Copy link to selected text" while highlighting `elle a brisé`, I get `#:~:text=briseelle a brisenous`, which is incorrect; it's not the text I've highlighted and it doesn't make any sense.

I've tried using the prefix and suffix as... a prefix and a suffix according to the [`README.md`](https://github.com/GoogleChromeLabs/link-to-text-fragment#background) (`#:~:text=brise-,elle a brise,-nous`), but that doesn't work either.

The previous and next lines seems to be merged with the first and last words respectively regardless of the `<br />` separating them. Not only that, but it also doesn't seem to be able to separate one word from its prefix & suffix.

**Comment by bokand** [comment]
Not sure about the "Copy link to selected text" issue, but both:

[https://leconjugueur.lefigaro.fr/conjugaison/verbe/briser_feminin.html#:~:text=brise-,elle a brise,-nous](https://leconjugueur.lefigaro.fr/conjugaison/verbe/briser_feminin.html#:~:text=brise-,elle%20a%20brise,-nous)

and

[https://leconjugueur.lefigaro.fr/conjugaison/verbe/briser_feminin.html#:~:text=elle a brisé](https://leconjugueur.lefigaro.fr/conjugaison/verbe/briser_feminin.html#:~:text=elle%20a%20brisé)

Work for me in Chrome 91.0.4472.114. Do the links above not create a highlight for you?

**Comment by NatoBoram** [comment]
Works on Edge 91.0.864.59 but not in Firefox 90.0b12

**Comment by tomayac** [comment]
On Firefox, we use a [polyfill](https://github.com/GoogleChromeLabs/text-fragments-polyfill). Could you please file the issue [here](https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues)? Thanks!

The HTML is relatively nasty (but correct) here, so there may actually be a bug in the implementation of the fragment generation.

```html
<p>j'ai bris<b>é</b><br>tu as bris<b>é</b><br>elle a bris<b>é</b><br>nous avons bris<b>é</b><br>vous avez bris<b>é</b><br>elles ont bris<b>é</b></p>
```

**Comment by tomayac** [comment]
Actually, let me file the issues myself. Never mind.

**Comment by tomayac** [comment]
See https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/75 and https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/76.
