### ISSUE TITLE
Safari Extension Doesn't Work

### ISSUE THREAD

**Issue by Bon-saiGecko** [GoogleChromeLabs/link-to-text-fragment#43]
Attempting to copy the link to any text will copy nothing. I have attempted with both rich and raw modes. I'm using Safari 15 on MacOS Monterey. 
![image](https://user-images.githubusercontent.com/13684891/134839024-574fbe4c-41dd-407b-b1d9-bad57ebe4d3f.png)

**Comment by tomayac** [comment]
Thanks for reporting this issue. There seem to be some changes how extensions work under the hood in Monterey and Safari 15. I'm looking into it.

**Comment by Bon-saiGecko** [comment]
Is there an update on this yet?

**Comment by tomayac** [comment]
Sorry, not yet, but it's still on my radar.

**Comment by tomayac** [comment]
I believe https://github.com/GoogleChromeLabs/link-to-text-fragment/commit/d0ff3a43072f7884bb1ae9b249654c2641829b91 fixed the issue. I'm now [fighting with App Store Connect](https://twitter.com/tomayac/status/1457807620073480203). Any help appreciated if you have experience with the issue from the tweet.

**Comment by Bon-saiGecko** [comment]
I don't know much about releasing apps, sorry.

**Comment by Bon-saiGecko** [comment]
Were you able to get this through App Store Connect then?

**Comment by tomayac** [comment]
Whenever I try to tackle this, I'm stuck for an unproductive hour and end up looking up obscure error messages `:-(`, so the answer unfortunately is still "no".

**Comment by Bon-saiGecko** [comment]
that doesn't sound fun :(
