### ISSUE TITLE
Chrome Extension is disabled when running CCleaner Custom Clean

### ISSUE THREAD

**Issue by Mike-B2021** [GoogleChromeLabs/link-to-text-fragment#44]
As per title - all the information is here   

https://community.ccleaner.com/topic/61192-chrome-extension-is-disabled-when-running-ccleaner-custom-clean/
(Password not required to read)

Please contact me for further information if needed. Tnx

**Comment by tomayac** [comment]
I am not in a position to judge external software, but as a user I have seen CCleaner ads in spurious sites and personally wouldn't feel comfortable installing it on my own computer. The recommended way to "clean" your Chrome profile is outlined in this [help article](https://support.google.com/chrome/answer/2765944#zippy=%2Cremove-malware-from-your-computer-windows).
