### ISSUE TITLE
Not working with mutation (German Umlaut (ä,ö,ü))

### ISSUE THREAD

**Issue by Daniel-at-git** [GoogleChromeLabs/link-to-text-fragment#47]
Cannot select text with German mutation (e.g ä,ö,ü)

If you try to link to
"bestätigt, nur um die offensichtliche Forschungsarbeit rund um autonome Systeme wird kein Geheimnis gemacht"

in
[https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html](https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html)

You get
[https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html#:~:text=bestatigt%2C%20nur%20um%20die%20offensichtliche%20forschungsarbeit%20rund%20um%20autonome%20systeme%20wird%20kein%20geheimnis%20gemacht](https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html#:~:text=bestatigt%2C%20nur%20um%20die%20offensichtliche%20forschungsarbeit%20rund%20um%20autonome%20systeme%20wird%20kein%20geheimnis%20gemacht)

and it's not working. The mutations are not included in "bestätigt". If I modify "bestatigt" to "bestätigt" in the URL like this
[https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html#:~:text=bestätigt%2C%20nur%20um%20die%20offensichtliche%20forschungsarbeit%20rund%20um%20autonome%20systeme%20wird%20kein%20geheimnis%20gemacht](https://www.heise.de/news/Apple-heuert-Teslas-ehemaligen-Autopilot-Director-an-6260442.html#:~:text=bestätigt%2C%20nur%20um%20die%20offensichtliche%20forschungsarbeit%20rund%20um%20autonome%20systeme%20wird%20kein%20geheimnis%20gemacht)

it's working fine.

**Comment by tomayac** [comment]
Looks like this problem has been fixed in Chrome 95. It's working fine for me here, and also with all other umlaut links that I checked just now.

<img width="647" alt="Screen Shot 2021-11-09 at 10 21 02" src="https://user-images.githubusercontent.com/145676/140897208-94de7d57-ef6a-460d-8ccc-666215623e18.png">

Viele Grüße,
Tom

**Comment by Daniel-at-git** [comment]
I'm running Chrome 95.0.4638.69
The issue seems to occur only with "uBlock Origin" addon. If I turn "uBlock Origin" off it's working fine.

I'm going to analyse "uBlock Origin" or going to open an issue there.

Thanks!

**Comment by tomayac** [comment]
If it helps, I had the same extension on when I tested.

**Comment by Daniel-at-git** [comment]
Invested some more time and reset uBlock. Now it's working :-o
Thanks for the hint!

**Comment by tomayac** [comment]
Thanks for letting me know. Glad it's working now!
