### ISSUE TITLE
This really should be a default chromium feature m

### ISSUE THREAD

**Issue by LifeIsStrange** [GoogleChromeLabs/link-to-text-fragment#48]

**Comment by tomayac** [comment]
It is a default Chromium feature now. It wasn’t when the extension was created. The extension lets you choose between rich and plain link copying, the built-in feature always copies the plain link.

**Comment by LifeIsStrange** [comment]
@tomayac great :) although I don't see this exposed on android :(

**Comment by tomayac** [comment]
It's not exposed quite yet, that's true. You can follow implementation progress by looking at https://bugs.chromium.org/p/chromium/issues/list?q=label%3Ash-clank.

**Comment by LifeIsStrange** [comment]
@tomayac bruh your link doesn't yield any result, and latest chrome canary on Android doesn't seem to expose copy url to sélection. It's been a year, please the world needs tewt fragments.
How else can I send a relevant section of a scientific paper on forum without readers being lost..

**Comment by LifeIsStrange** [comment]
Thank you tomayac!
