### ISSUE TITLE
Suggestion: Add option to make a bookmark

### ISSUE THREAD

**Issue by betweenthefog** [GoogleChromeLabs/link-to-text-fragment#49]
I just found this while looking for ways to bookmark flower seed entries on a plain-text website. Works great in Firefox 95 so far. Thank you for supporting multiple clients!

One suggestion, if possible, is for there to be an option to create a bookmark of the highlighted text, with the bookmark's name being the highlighted text itself. 

I can do this myself by creating the bookmark ahead of time and copying and pasting the text in it, but this could cut down on the amount of copying and pasting to get the same result. It'd be understandable if this isn't possible due to security issues or it being outside the scope of the extension, though.

**Comment by tomayac** [comment]
I have routed this to become a core browser feature request: https://crbug.com/1285782.
