### ISSUE TITLE
Optionally URL-encode parentheses

### ISSUE THREAD

**Issue by kriegaex** [GoogleChromeLabs/link-to-text-fragment#51]
The Chrome extension created this link for me:
https://wiki.eclipse.org/Tycho/Reference_Card#:~:text=include%20source%20bundles)-,target%20runtime%20environment,-Specify%20which%20environments

Do you see the closing parenthesis ")" in the URL? That is a problem, just like an opening parenthesis, if you want to use that URL in a markdown documentlink, because the format is `[My description](https://my.url.org/foo/bar)`. Now when using the URL in a link directly here on GitHub, it looks like this:

[My description](https://wiki.eclipse.org/Tycho/Reference_Card#:~:text=include%20source%20bundles)-,target%20runtime%20environment,-Specify%20which%20environments)

If I manually URL-encode the closing parenthesis as `%29`, the link looks OK:

[My description](https://wiki.eclipse.org/Tycho/Reference_Card#:~:text=include%20source%20bundles%29-,target%20runtime%20environment,-Specify%20which%20environments)

So please, enable the user to specify a list of characters which should be URL-encoded by default.

**Comment by tomayac** [comment]
Migrated over to https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/115, the repo where link creation is dealt with.
