### ISSUE TITLE
Not highlighting text on Chrome

### ISSUE THREAD

**Issue by guihkx** [GoogleChromeLabs/link-to-text-fragment#58]
When trying to highlight the following text:

```
March 29th, 2022 - Windows 473.33, Linux 470.62.26
```

From this page: https://developer.nvidia.com/vulkan-driver

Your extension generates the following URL:

https://developer.nvidia.com/vulkan-driver#:~:text=march%2029th%2C%202022%20-%20windows%20473.33%2C%20linux%20470.62.26

When you open the URL above on Firefox 98.0.2, it highlights the text successfully, but the same does not happen on Chrome 100.0.4896.60.

Using Chrome's built-in "Copy link to highlight" feature, this URL is generated instead (and it works on both Firefox and Chrome):

https://developer.nvidia.com/vulkan-driver#:~:text=March%2029th%2C%202022%20%2D%20Windows%20473.33%2C%20Linux%20470.62.26

Maybe it could help you find a solution.

Thank you for this extension by the way!

**Comment by tomayac** [comment]
Closing in favor of https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/132. Link generation happens outside of the extension code via the polyfill library.
