### ISSUE TITLE
Safari extension: mark iPad as a compatible device

### ISSUE THREAD

**Issue by Stvad** [GoogleChromeLabs/link-to-text-fragment#62]
The current version of the extension is published mac-only, and it’d be great if one could install it on iPad too !

**Comment by tomayac** [comment]
Sorry for the delay here. Unfortunately we keep having trouble with the Xcode App Store submission process and can't publish an update. The extension on Safari is broken for unknown reason anyway at the moment, as reported via #69. I'm closing this Issue and add a note to #69 about marking it iPad compatible.
