### ISSUE TITLE
Is it possible to create linked To text fragment for A reference manager called readcube.com.

### ISSUE THREAD

**Issue by jakkaas** [GoogleChromeLabs/link-to-text-fragment#64]
I am using a web reference manager called papers readcube.com. It uses a enhanced PDF reader which uses its own right click menu. I am using a shortcut key assign to link to text fragment for creating link to its text in its PDF. But the text link is lost after a click. Is there any way to retain the link and the highlight to such web-based reference manager? Thanks

**Comment by tomayac** [comment]
I registered for a 30 day trial for the app and looked for one of my papers to create a test link: [`https://www.readcube.com/library/0c6c7fdc-ab03-4aee-9d2a-e1c6ec16637a:bb6a07d0-31e3-4ab8-a1c0-a529232c5861#:~:text=AdAlyze-,Redux,-%3A%20Post%2DClick%20and`](https://www.readcube.com/library/0c6c7fdc-ab03-4aee-9d2a-e1c6ec16637a:bb6a07d0-31e3-4ab8-a1c0-a529232c5861#:~:text=AdAlyze-,Redux,-%3A%20Post%2DClick%20and). It seems like the link is gated on login, and not sure if my links would work for anyone else.

Looking at the PDF reader, they seem to convert the PDF to HTML, so in theory it could work, but it looks like the creation is taking a little too long for the browser's built-in text fragment finder to work (there is a spinner, and probably the text fragment finder runs while the spinner is still shown).

If you know how this works with the app, try creating a public PDF link that people on the Chrome team can access without login, and then file a new Chromium bug via [new.crbug.com](https://new.crbug.com/) where you ask for this site to be supported for the text fragment feature. It's not an issue with the extension.
