### ISSUE TITLE
Failure message is imprecise/wrong

### ISSUE THREAD

**Issue by goleary** [GoogleChromeLabs/link-to-text-fragment#65]
When I try to make [a particular text fragment](https://oll.libertyfund.org/title/macaulay-critical-and-historical-essays-vol-1#:~:text=to%20say%2C%20that-,Lord%20Byron%20could%20exhibit,characters%2C%20his%20only%20two,-characters%2C%20he%20could) on a [particular document](https://oll.libertyfund.org/title/macaulay-critical-and-historical-essays-vol-1) that is super long the extension fails and I am presented with a message that says:

> Couldn't create a unique link, please select a longer sequence of words.

The thing is the [fragment-generation-utils](https://github.com/GoogleChromeLabs/text-fragments-polyfill/blob/c036420683f672d685e27415de0a5f5e85bdc23f/src/fragment-generation-utils.js#L43) returns a status which specifies numerous different reasons for fragment generation failure.

```
export const GenerateFragmentStatus = {
  SUCCESS: 0,            // A fragment was generated.
  INVALID_SELECTION: 1,  // The selection provided could not be used.
  AMBIGUOUS: 2,  // No unique fragment could be identified for this selection.
  TIMEOUT: 3,    // Computation could not complete in time.
  EXECUTION_FAILED: 4  // An exception was raised during generation.
};
```

But the extension [reports them to the user](https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/c0d927896289e82154fa2db15739036c5700ac74/content_script.js#L46) all in the same way.

![image](https://user-images.githubusercontent.com/16123225/174901565-f982f328-6125-4b5f-ae4b-180997e4840e.png)

In the instance referenced above the util fails due to timeout. When I overwrite the `timeoutDurationMs` to be 2000 (instead of 500) I am able to obtain [a link with text fragment](https://oll.libertyfund.org/title/macaulay-critical-and-historical-essays-vol-1#:~:text=to%20say%2C%20that-,Lord%20Byron%20could%20exhibit,characters%2C%20his%20only%20two,-characters%2C%20he%20could).

**Comment by tomayac** [comment]
Fixed via https://github.com/GoogleChromeLabs/link-to-text-fragment/commit/3c5da4ed89d0fe2528ada436532a9dae30f49a3c.
