### ISSUE TITLE
Wrong link with rich text format with raw url

### ISSUE THREAD

**Issue by brunoelgrande** [GoogleChromeLabs/link-to-text-fragment#67]
On chrome and mac os and windows 10, if I use rich text with raw URL option 

When I paste directly to a browser address bar, I get a functioning link toward the exact place I want.  

> Exemple : https://web.dev/text-fragments/#:~:text=boldly%20link%20where%20no%20one%20has%20linked%20before%3A%20text%20fragments

But if I paste the rich text with URL link first in a document and then click on the link: 

> Boldly link where no one has linked before: Text Fragments [🔗](https://web.dev/text-fragments/#:~:text=boldly%2520link%2520where%2520no%2520one%2520has%2520linked%2520before%253A%2520text%2520fragments)

> https://web.dev/text-fragments/#:~:text=boldly%2520link%2520where%2520no%2520one%2520has%2520linked%2520before%253A%2520text%2520fragments

I get %2520 instead of %20 and I can't get directly to the highlighted area. 

Thaks for the help, Bruno

**Comment by tomayac** [comment]
Fixed via https://github.com/GoogleChromeLabs/link-to-text-fragment/commit/3c5da4ed89d0fe2528ada436532a9dae30f49a3c.
