### ISSUE TITLE
Needs a welcome message telling the user how to enable permissions

### ISSUE THREAD

**Issue by James-E-A** [GoogleChromeLabs/link-to-text-fragment#68]
I've got a broken URL:

* https://sockpuppet.org/blog/2014/04/30/you-dont-want-xts/#:~:text=You%20can%E2%80%99t%20authenticate%20the%20data,the%20disk%2E&text=Encryption%20without%20authentication,bindshell
* https://sockpuppet.org/blog/2014/04/30/you-dont-want-xts/#:~:text=You%20can%E2%80%99t%20authenticate%20the%20data,the%20disk%2E

Tested on Edge 102.0.1245.44 (working); Chrome 103.0.5060.66 (working); Firefox 102.0 + LtTF 2.3.3 (not working)

**Comment by JamesTheAwesomeDude** [comment]
Replacing the right single quotation mark with an ASCII apostrophe didn't make LtTF accept it, either:

* https://sockpuppet.org/blog/2014/04/30/you-dont-want-xts/#:~:text=You%20can%27t%20authenticate%20the%20data,the%20disk%2E

**Comment by JamesTheAwesomeDude** [comment]
*Actually, these work -- the problem is that, out-of-the-box, the add-on **doesn't have the permissions it needs to function**. I had to click on the toolbar once to get it to ask for these permissions.

**Comment by tomayac** [comment]
The instructions are [right in the description](https://addons.mozilla.org/en-US/firefox/addon/link-to-text-fragment/#:~:text=You%20will%20be%20asked%20if%20you%20want%20to%20grant%20access%20to%20http%3A//*/*%20and%20https%3A//*/*%20when%20you%20create%20a%20link.%20This%20is%20to%20optionally%20add%20a%20polyfill%20for%20the%20Text%20Fragment%20feature.%20The%20polyfill%20is%20still%20work%20in%20progress.).

<img width="610" alt="Screen Shot 2022-06-30 at 09 41 27" src="https://user-images.githubusercontent.com/145676/176621166-a8405190-d05f-43fb-86b3-e492019d3633.png">
