### ISSUE TITLE
Please enable Discussion.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [GoogleChromeLabs/link-to-text-fragment#70]
My rationale is available at "https://github.com/8go/matrix-commander/issues/68#issue-1237645245".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
However, because that is not active (yet, hopefully) I ask how "Copy a rich text link." and "Copy the raw URL." are different.

**Comment by tomayac** [comment]
Imagine you want to link to the text "Example Domain" on https://example.com/.

- Raw link: https://example.com/#:~:text=example%20domain,-This
- Rich link: [Example Domain](https://example.com/#:~:text=example%20domain,-This)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Ah, so Rich text automatically encapsulates it within Markdown, @tomayac?

**Comment by tomayac** [comment]
Not Markdown, the actual HTML that you see on GitHub. 

I prefer managing discussions in Issues for now. It's fine to open one for purely discussion.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Brilliant. I must say that I prefer HTML significantly.
