### ISSUE TITLE
Operate via any URI-scheme.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [GoogleChromeLabs/link-to-text-fragment#72]
Even [#extensions-on-chrome-urls](chrome://flags/#extensions-on-chrome-urls) does not allow this extension to support `chrome:`, as "https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/71#issuecomment-1206474064:~:text=the chrome%3A protocol is not supported by the extension." confirms. Consequently, I request that it be allowed to, because it would significantly ease configuration-tutorials since `chrome:` supports fragments already..

**Comment by tomayac** [comment]
Since this is more a Chrome feature and not an extension feature, please continue the discussion over on https://crbug.com/1344820. I have filed for additional protocols to be supported there already. Thank you!
