### ISSUE TITLE
Can I get the link to selection in code?

### ISSUE THREAD

**Issue by eduOS** [GoogleChromeLabs/link-to-text-fragment#73]
The link can be copied into the clipboard once I hit the copy link to highlight in the context menu, but I wonder if I can get the link in dev console? How can I get it?

**Comment by tomayac** [comment]
You can fork the extension code and log the URL to the clipboard here:

https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/f2706bc13e69e6ae386458fd044d7332636617ef/content_script.js#L91
