### ISSUE TITLE
Idea - When no text selected, copy link with title of the page

### ISSUE THREAD

**Issue by gmmazza** [GoogleChromeLabs/link-to-text-fragment#74]
I'm on Windows. 
Occasionally, I need to copy a link from a webapp bit the access to the link text could be really cumbersome. Also for any webpage opened, when I press the assigned hotkey, "link to text fragment" without text selected. Could make a straightforward to copy links. Thanks.

**Comment by tomayac** [comment]
The entire idea of this extension is to link to selected text. Your idea might be an idea for a separate extension.
