### ISSUE TITLE
Errors out on highlights beginning with whitespace

### ISSUE THREAD

**Issue by ivyraine** [GoogleChromeLabs/link-to-text-fragment#75]
Hi, and thank you for the project! I've been trying it, but it appears that whenever a highlight begins with whitespace it errors with out either `AMBIGUOUS` or `TIMEOUT`, originating from `generateFragment()`.

**Comment by tomayac** [comment]
This is the same underlying issue as https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/135 in the library that is used by the extension in the background. Closing the present issue in favor of the referenced one.
