### ISSUE TITLE
Doesn't work on documents of Content-Type text/plain

### ISSUE THREAD

**Issue by robin-a-meade** [GoogleChromeLabs/link-to-text-fragment#76]
It was stated in #49 that this works in plain-text documents, but I can't get it to work.

I tried these plain text documents:

https://www.ietf.org/rfc/rfc2822.txt
https://tiswww.case.edu/php/chet/bash/CHANGES

**In Firefox**, the **Link to text fragment** extension allows me to **Copylink to selected text**, but it won't scroll to the text when I paste the resulting link into a new tab.

**Chrome** (no extension needed) allows me to **Copy link to highlight** but won't scroll to the text when I paste the resulting link into a new tab.

Is this supposed to work on documents of Content-Type _text/plain_? 

If not, the menu item should be disabled on documents of Content-Type _text/plain_.

**Comment by bokand** [comment]
This was the result of https://crbug.com/1270469 but I think text/plain should probably be supported. If you don't mind, please file a bug on crbug.com/new to support that and cc me (bokan@chromium.org), we can take a closer look there.

**Comment by robin-a-meade** [comment]
I filed https://crbug.com/1392548 
Sorry, I couldn't figure out how to add a cc.

**Comment by tomayac** [comment]
Closing the present Issue in favor of the Chromium bug.
