### ISSUE TITLE
Firefox 107.0 on Fedora: link-to-text doesn't appear in context menu

### ISSUE THREAD

**Issue by PenelopeFudd** [GoogleChromeLabs/link-to-text-fragment#77]
When I highlight some text and then right-click on it, Link-to-text doesn't appear on the context menu.

Fortunately, the toolbar button still works. :-)

**Comment by siffegh** [comment]
Sometimes it does not appear for me too. Disabling/re-enabling the addon fixes it for a while.

**Comment by Stvad** [comment]
Same story here - need to reinstall add-on to make the context menu link to appear =\

**Comment by Stvad** [comment]
Haven't realized that clicking the extension button in toolbar also works - that means one can set a KB shortcut to copy the fragment link! Probably should be highlighted in the readme

**Comment by tomayac** [comment]
Seems more of a Firefox issue than an issue with the extension itself. Might be worth [raising with Firefox](https://bugzilla.mozilla.org/enter_bug.cgi#h=dupes%7CFirefox).

**Comment by PenelopeFudd** [comment]
Perhaps, but they're likely going to say the plugin developer should be the one to file the bug report; we're just users with no technical insight into what's going wrong.

**Comment by Stvad** [comment]
this also happen only to the link to fragment extension (I think it’s connected to the FF or extension getting updated). 
Other extension don’t loose the context menu items, which suggests to me potentially a manifest issue or permission setup issue

**Comment by tomayac** [comment]
Since you have experienced the issue (I haven't), it's best if you file the bug, so the Firefox developers can ask you to test if potential fixes indeed fix the problem for you.
