### ISSUE TITLE
Text fragment in Bootsrap Offcanvas doesn't jump to the point in mobile mode 

### ISSUE THREAD

**Issue by Jonnas123** [GoogleChromeLabs/link-to-text-fragment#78]
I place text fragment link in Bootstrap offcanvas. It jumps to the correct point in desktop but not in mobile, it's not scrollable. I test normal anchor it works fine `<a href="https://mysite.com/#test">test anchor</a> <span id="test">test</span>`

**Comment by tomayac** [comment]
This is not a bug with the extension, but potentially a Chrome bug. Please file one at https://new.crbug.com and provide the exact links.
