### ISSUE TITLE
Scroll to text fails for fragments that include hyphenated words

### ISSUE THREAD

**Issue by jimmoffet** [GoogleChromeLabs/link-to-text-fragment#80]
Chrome 109.0.5414.87 (Official Build) (arm64)

**Succeeds:**
Highlighted text: `the user is made aware of the text match, such as with a`
[https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a](https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a)

**Fails:**
Highlighted text: `the user is made aware of the text match, such as with a high-contrast highlight`
[https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a%20high-contrast%20highlight](https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a%20high-contrast%20highlight)  

~~Seems like a bug in extension implementation, not in the text fragments implementation.~~ **EDIT:** I guess this is a matter of perspective, in any case, substituting `%2D` for the hyphen in the appropriate location(s) solves the problem.

**Succeeds:**
Highlighted text: `the user is made aware of the text match, such as with a high-contrast highlight`
[https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a%20high%2Dcontrast%20highlight](https://wicg.github.io/scroll-to-text-fragment/#:~:text=the%20user%20is%20made%20aware%20of%20the%20text%20match%2C%20such%20as%20with%20a%20high%2Dcontrast%20highlight)

**Comment by jimmoffet** [comment]
Just submitted #81

**Comment by tomayac** [comment]
Thanks for the contribution. If this is a problem, it should be fixed at the source. Could you please see https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues. Also note that there might be edge cases where a simple replacement won’t work. I’m closing the Issue here.
