### ISSUE TITLE
Dashes in selected text to create link from

### ISSUE THREAD

**Issue by Pheggas** [GoogleChromeLabs/link-to-text-fragment#83]
Hello. I discovered that dashes ( - ) could not be copied as a link (it wouldn't jump to selected text / highlight the text). Is there a possibility to fix this or it is just limitation of the technology?

**Comment by tomayac** [comment]
It's probably a limitation with the site in question, for example, that it's lazily dynamically generated via JavaScript only when the user scrolls or so. The technology _per se_ supports dashes (example link `https://www.iana.org/domains/reserved#:~:text=Policy%2Dreserved%20domains`.
