### ISSUE TITLE
Selection Error -- 'Couldn't create a unique link, please select a longer sequence of words'

### ISSUE THREAD

**Issue by davidmponder** [GoogleChromeLabs/link-to-text-fragment#84]
Hi, great tool, worked briefly but now it seems that I am getting a non-sensical error msg.
As when I try and do what is state, select a longer sequence of words it repeats.
Then I try the reverse logic and select less and it still is the same.

In addition this msg appears.

> (INVALID_SELECTION: The selection provided could not be used.)

After some further checking on other websites it seems this website is preventing a link from being created; why is that?

[VeVe Payout Details: What You Need To Know](https://medium.com/@VeVe-/veve-payout-details-what-you-need-to-know-23bb2a6bd26a)

Annotated error msg:
![image](https://user-images.githubusercontent.com/60014403/224550793-2cfdf773-d493-4a9a-9792-e7830f9d4a7c.png)

Hopefully we could get some feedback to explain what has happened and a solution/fix.

I am guessing there is some intentional functionality built in that prevents tool specifically like 'Link to Text Fragment' from working properly.

**Comment by tomayac** [comment]
I just successfully created a link with the extension: https://medium.com/@VeVe-/veve-payout-details-what-you-need-to-know-23bb2a6bd26a#:~:text=what%20is%20the%20payout%20feature%3F

The "Pen" icon has nothing to do with the extension. It's part of Medium's UI.

![Screenshot 2023-03-13 at 11 17 03](https://user-images.githubusercontent.com/145676/224673058-0c443175-756e-43cf-a727-fa648c50ef1b.png)
