### ISSUE TITLE
Provide a method for generating a method from a range instead of a selection

### ISSUE THREAD

**Issue by palenshus** [GoogleChromeLabs/link-to-text-fragment#85]
It would be convenient to be able to generate a frament from a range directly, instead of having to go through a Selection. It'd be a simple refactoring, and would make the library more flexible. I'm thinking something like:

```js
const generateFragmentFromRange = (range, startTime = Date.now()) => { ...
```

**Comment by tomayac** [comment]
Please suggest this as a [new Issue in the library repo](https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues) that this present extension uses. Closing here.

**Comment by palenshus** [comment]
Created https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/149, thanks!
