### ISSUE TITLE
Unable to link to text inside table

### ISSUE THREAD

**Issue by gaiking-uk** [GoogleChromeLabs/link-to-text-fragment#86]
Hi, I tried to manually generate a text fragment link URL manually and by using [Edge extension](https://microsoftedge.microsoft.com/addons/detail/link-to-text-fragment/pmdldpbcbobaamgkpkghjigngamlolag), however even though the extension highlighted the selected text and generated a link, the generated URL would not trigger the ```scroll-to-text-fragment``` functionality.

- **Page**: https://imagemagick.org/script/download.php
- **Text Fragment**: 
  1. Plain text: Portable ARM64 static at 16 bits-per-pixel component with
  2. Text including ```<A HREF>```: Portable Win64 static at 16 bits-per-pixel component with enabled. Just copy to your host and run (no installer, no Windows registry entries).
  3. Text inside ```<A HREF>```: -portable-Q16-HDRI-x64.zip
- **URL:** [https://imagemagick.org/script/download.php#:~:text=portable%20win64%20static%20at%2016%20bits-per-pixel%20component%20with](https://imagemagick.org/script/download.php#:~:text=portable%20win64%20static%20at%2016%20bits-per-pixel%20component%20with)

![TextFragementLink Screenshot](https://user-images.githubusercontent.com/37931190/231166781-c47cd24e-02a7-4d39-ae2a-d34a565d0916.jpg)

The only thing that I can think that may be interfering with it, is that the text was inside a ```<TD>``` tag...

**Comment by tomayac** [comment]
The browser built-in "Copy link to highlight" feature creates this link:

https://imagemagick.org/script/download.php#:~:text=x64%2Dstatic.exe-,Win64%20static%20at%2016%20bits%2Dper%2Dpixel%20component%20with,-high%20dynamic%2Drange

The extension creates this link:

https://imagemagick.org/script/download.php#:~:text=x64-static.exe-,win64%20static%20at%2016%20bits-per-pixel%20component%20with,-high%20dynamic-range

Could you please file this as a new Issue in the [repo of the text-fragments](https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues)? I'm closing the present Issue.
