### ISSUE TITLE
[feature-request] add to mobile/android

### ISSUE THREAD

**Issue by craziedde** [GoogleChromeLabs/link-to-text-fragment#90]
Good morning,

Can you add ability to "link-to-text-fragment" via android browser?

Thank you for very useful product.

Ed

**Comment by tomayac** [comment]
Chrome for Android doesn’t support extensions, so the question doesn’t arise in the context of this repo. If you want to ask for native browser support (that is, not via an extension), please file a [new Chromium bug](https://new.crbug.com/).

**Comment by craziedde** [comment]
Work around found and added to initial post

> Good morning,
> 
> Can you add ability to "link-to-text-fragment" via android browser?
> 
> Thank you for very useful product.
> 
> Ed
> 
> [EDIT] Work around found:
> 
> 1. Install Kiwi browser [here](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en_US)
> 2. Now can install Link-to-text-fragment [here](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg)
> 3. To execute extension in Kiwi browser → select text → 3-dots → "Link to Text Fragment"
>    ![image](https://user-images.githubusercontent.com/2974843/255405300-c37e88c0-8caf-42b6-8398-fc3db2c28edd.png)

Work around found and added to initial post

**Comment by tomayac** [comment]
Yes, if using a different browser that supports extensions is an acceptable workaround, then this option certainly exists.

**Comment by krystian3w** [comment]
AdGuard can load `user.js` version.

Maybe possible convert addon to one user script.
