### ISSUE TITLE
Do not remove pre-existent `#.*:` section of URI.

### ISSUE THREAD

**Issue by rokejulianlockhart** [GoogleChromeLabs/link-to-text-fragment#92]
If I use the extension on https://www.myheritage.com/FP/memberEditProfile.php?s=781598791&memberID=1085838471&sourceList=#notificationPanelAnchor:~:text=I%20am%20researching%3A-,my%20email%20,-Email%3A at https://www.myheritage.com/FP/memberEditProfile.php?s=781598791&memberID=1085838471&sourceList=#notificationPanelAnchor, [`notificationPanelAnchor`](https://regex-generator.olafneumann.org/?sampleText=https%3A%2F%2Fwww.myheritage.com%2FFP%2FmemberEditProfile.php%3Fs%3D781598791%26memberID%3D1085838471%26sourceList%3D%23notificationPanelAnchor%3A~%3Atext%3DI%2520am%2520researching%253A-%2Cmy%2520email%2520%2C-Email%253A&flags=P&selection=95%7CCharacter,96%7CAlphanumeric%20characters,119%7CCharacter) is removed, resulting in https://www.myheritage.com/FP/memberEditProfile.php?s=781598791&memberID=1085838471&sourceList=#:~:text=I%20am%20researching%3A-,my%20email%20,-Email%3A.

This is erroneous, because that part of the URI *has meaning*, especially in circumstances where it isn't simply used to communicate where scroll the page to. However, in the instances that it is, such as at https://en.wikipedia.org/wiki/Allied_invasion_of_Italy#Salerno_landings, it is a useful fallback for browsers where fragment support is unavailable.

**Comment by tomayac** [comment]
This has been discussed in https://github.com/WICG/scroll-to-text-fragment/issues/75. The spec also [has a section about this question](https://wicg.github.io/scroll-to-text-fragment/#determine-if-fragment-id-is-needed). There are two cases: the  first case is the one where the page actually has an element with the hash ID, like `<h1 id="example">Example</h1>`, and the second case it the one where the hash is used as a JavaScript-based router, but doesn't appear in the page, like `https://example.com/#page1`. Your example seems to be the latter, in which case _"If the UA cannot reliably determine an appropriate fragment to fallback to, it should remove the fragment id from the URL"_ kicks in.

**Comment by rokejulianlockhart** [comment]
@tomayac, https://github.com/WICG/scroll-to-text-fragment/issues/75#issue-537668097 discusses the behaviour of the search functionality when the fragment is included with the directive. I don't care about that; I just want this extension to not remove that portion because it causes issues when the fragment isn't used for searching the page. Fragments are frequently used for other purposes, so they're as important a part of any URI as any other.

**Comment by tomayac** [comment]
Just submitted v2.4.0 to the store that preserves potentially existing hashes.
