### ISSUE TITLE
Copied Link to Selected Text Appearing as a Link Rather Than the Text

### ISSUE THREAD

**Issue by shiggles08** [GoogleChromeLabs/link-to-text-fragment#93]
Hi there, 

Previously when using this extension, when I pasted the link it would appear as text from the webpage. Unfortunately, it is no longer doing this and when I paste the link it appears as the URL rather than a hyperlinked fragment of text. It does still highlight and brings you directly to the highlight text, but it isn't formatting properly when using this extension in emails etc. 

E.g. https://www.buyacar.co.uk/cars/family-cars/hatchbacks/362/what-is-a-hatchback#:~:text=back%20seats%20that%20can%20slide

Is there a way to resolve this on my end?

Thank you for any guidance!

**Comment by tomayac** [comment]
This is unfortunately a known issue at the moment. The reason is that extension service workers can't call the clipboard API since they can't be focused. Please track https://crbug.com/1404835.
