### ISSUE TITLE
Text fragment link converts upper-case to lower-case in Firefox

### ISSUE THREAD

**Issue by carlgieringer** [GoogleChromeLabs/link-to-text-fragment#94]
Hi,

When I create a text fragment link in Firefox, the fragment is all lower-case despite the source text containing upper-case characters.

For example if I try to create a text fragment link for this text from [this site](https://www.geekwire.com/2023/artists-giant-troll-sculptures-bring-whimsy-to-seattle-area-woods-and-a-message-about-waste/):

> Danish environmental artist and storyteller Thomas Dambo and a team of volunteers have completed four of the six trolls that are part of a public exhibition titled [“Northwest Trolls: Way of the Bird King.”](https://www.nwtrolls.org/) The project is funded in part by the Paul G. Allen Family Foundation.

I get https://www.geekwire.com/2023/artists-giant-troll-sculptures-bring-whimsy-to-seattle-area-woods-and-a-message-about-waste/#:~:text=danish%20environmental%20artist%20and%20storyteller%20thomas%20dambo%20and%20a%20team%20of%20volunteers%20have%20completed%20four%20of%20the%20six%20trolls%20that%20are%20part%20of%20a%20public%20exhibition%20titled%20%E2%80%9Cnorthwest%20trolls%3A%20way%20of%20the%20bird%20king.%E2%80%9D%20the%20project%20is%20funded%20in%20part%20by%20the%20paul%20g.%20allen%20family%20foundation.

This is the text decoded:

> danish environmental artist and storyteller thomas dambo and a team of volunteers have completed four of the six trolls that are part of a public exhibition titled “northwest trolls: way of the bird king.” the project is funded in part by the paul g. allen family foundation

Where you can see that all characters are lower-case despite there being upper-case characters in the source.

System info:

* macOS Ventura 13.1 (22C65)
* Firefox 117.0 (64-bit)
* Extension: Version 2.3.2 (Last Updated August 10, 2023)

**Comment by tomayac** [comment]
Note that [Matches are case-insensitive](https://developer.mozilla.org/en-US/docs/Web/Text_fragments#usage_notes), so that’s all fine.
