### ISSUE TITLE
Doesn't work on `https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GoogleChromeLabs/link-to-text-fragment#99]
It indefinitely hangs on line 48126 of https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry, using https://addons.mozilla.org/firefox/downloads/file/3969185/link_to_text_fragment-2.3.2.xpi on https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0.1-1.1.x86_64.rpm on `cpe:/o:opensuse:tumbleweed:20240310`.

**Comment by tomayac** [comment]
Same reason as https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/98. Please use the built-in feature for now. Sorry I don't have a better answer.
